### ISSUE TITLE
NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [joshka/tui-markdown#8]
Hi,

I've just packaged `markdown-reader` for NetBSD :)

![2024-02-27-204826_1366x768_scrot](https://github.com/joshka/tui-markdown/assets/90570748/455ef888-95f2-4e32-a88b-9dac3908ad64)

I wonder, though if, I should wait with merging the package into the main branch until the TODO list has been fixed.
Currently, only simple `.md` files will render, _e.g._ your own `README.md` doesn't.

```
The application panicked (crashed).
Message:  not yet implemented
Location: tui-markdown/src/lib.rs:115

NOTE: Please check the TODO section in the README for a list of missing features.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Exception: mdr exited with 101
  [tty 1]:1:1-14: mdr README.md
```

What do you think?

**Comment by joshka** [comment]
I appreciate your eagerness! This is way too new and experimental to be worth considering for packaging yet. I mostly published to crates.io in order to reserve the package names.

**Comment by 0323pin** [comment]
That's fine, that's why I asked.
Feel free to ping me when/if you think it's ready 😄 

For now, I've added the package to our _wip_ repo, https://mail-index.netbsd.org/pkgsrc-wip-changes/2024/02/27/msg029601.html
This is safer than keeping it locally.

**Comment by joshka** [comment]
Sounds good - closing this for now (I'll ping you on this issue when it's more ready for consumption)
